// <auto-generated />
using Application.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Application.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Application.Domain.Entities.ScheduleEntity", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CeremonyEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CeremonyStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcertStart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GateOpenEnd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GateOpenStart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreShowEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreShowStart")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventId");

                    b.ToTable("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
